---
title: "Soccer Player Birth Months"
description: |
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

library(tidyverse)
library(knitr)


```


```{r}
x <- read_csv("birthdates.csv",
              col_types = cols(
  value = col_character()
))
```


```{r}
x %>% 
  mutate(date = parse_date(str_sub(value, 2, 11))) %>% 
  mutate(raw_month = months(date)) %>% 
  mutate(month = parse_factor(raw_month, levels = month.name)) %>% 
  group_by(month) %>% 
  summarize(total = n()) %>% 
  ggplot(aes(x = fct_rev(month), y = total)) +
    geom_col() +
    coord_flip() +
    labs(title = "Euro 2020 Soccer Player Birth Months",
         subtitle = "Elite players are not more likely to be born in January",
         caption = "Data from Wikipedia",
         x = NULL,
         y = "Number")
  
```

